[workspace]
resolver = "2"

members = ["day-*", "shared"]
default-members = ["day-*"]

[workspace.dependencies]
glam = "0.24.2"
itertools = "0.12.0"
miette = { version = "5.10", features = ["fancy"] }
nom = "7.1.3"
